from selenium.webdriver.common.by import By


class Locators:
    BUTTON_LOGIN_IN_HEADER = (By.XPATH, ".//button[text()='Вход и регистрация']")
    BUTTON_GO_TO_REGISTER = (By.XPATH, ".//button[text()='Нет аккаунта']")
    FIELD_EMAIL = (By.NAME, "email")
    FIELD_REGISTER_EMAIL_ERROR = (By.XPATH, ".//*[@name='email']//..//../following-sibling::span")
    FIELD_PASSWORD = (By.NAME, "password")
    FIELD_SUBMIT_PASSWORD = (By.NAME, "submitPassword")
    FIELDS_WITH_ERROR = (By.XPATH, ".//div[contains(@class, 'input_inputError')]")
    BUTTON_REGISTER = (By.XPATH, ".//button[text()='Создать аккаунт']")
    USERNAME_IN_HEADER = (By.CSS_SELECTOR, ".profileText.name")
    AVATAR_IN_HEADER = (By.CLASS_NAME, "circleSmall")
    AVATAR_IN_HEADER_SVG = (By.CLASS_NAME, "svgSmall")
    BUTTON_LOGOUT = (By.XPATH, ".//button[text()='Выйти']")
    BUTTON_LOGIN_IN_AUTH_FORM = (By.XPATH, ".//button[text()='Войти']")
    BUTTON_CREATE_LISTING = (By.XPATH, ".//button[text()='Разместить объявление']")
    TITLE_FORM_CREATE_LISTING = (By.XPATH, ".//div[contains(@class, 'popUp_titleRow')]")
    FIELD_LISTING_NAME = (By.NAME, "name")
    FIELD_LISTING_DESCRIPTION = (By.XPATH, ".//textarea[@name='description']")
    FIELD_LISTING_PRICE = (By.NAME, "price")
    DROPDOWN_LISTING_CATEGORY_BUTTON_OPEN_LIST = (By.XPATH, ".//input[@name='category']//..//button")
    DROPDOWN_LISTING_CATEGORY_LIST_VALUES = (By.XPATH, ".//input[@name='category']//..//following-sibling::div//button")
    DROPDOWN_LISTING_CITY_BUTTON_OPEN_LIST = (By.XPATH, ".//input[@name='city']//..//button")
    DROPDOWN_LISTING_CITY_LIST_VALUES = (By.XPATH, ".//input[@name='city']//..//following-sibling::div//button")
    RADIOBUTTON_LISTING_PRE_OWNED = (By.XPATH, ".//input[@value='Б/У']//following-sibling::div")
    BUTTON_LISTING_PUBLISH = (By.XPATH, ".//button[text()='Опубликовать']")
    BLOCK_CREATED_PRODUCT_CARD = (By.XPATH, ".//h1[text()='Мои объявления']/following-sibling::div")
    CREATED_PRODUCT_CARD_TITLE = (By.XPATH, "//div[@class='about']//h2")
    CREATED_PRODUCT_CARD_CITY = (By.XPATH, "//div[@class='about']//h3")
    CREATED_PRODUCT_CARD_PRICE = (By.XPATH, "//div[@class='price']//h2")